# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6af4b489c5c3cb46e00352be39830e0308c30e601bc63722c0d8b537f850826a1971a5ffe121f88230979ef14f1ff532ed0bce1c56359c53b66fba7c91b7e73b

test:
  secret_key_base: 4a3c64e42e38e0d814bca5bcbf331df4575c25ae11c25c9bfe4f2cda369f7d6efeecdf49bdfb8c5d202e7acef265f16aad99d74933222c2313249b53db1835b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
